 function setBiggerText() {
                            document.getElementById('demo').style.fontSize = '70px';
                        }
                        function setSmallerText() {
                            document.getElementById('demo').style.fontSize = '20px';
                        }
                        function setNormalText() {
                            document.getElementById('demo').innerHTML = Date()
                            document.getElementById('demo').style.fontSize = '35px';
                        }